### ISSUE TITLE
Reload Command Error

### ISSUE THREAD

**Issue by apotenza92** [sisoe24/hammerspoon-vscode#1]
Hi, unsure what I'm doing wrong here. 

![Untitled](https://user-images.githubusercontent.com/53612685/151725526-1d2b1831-a9bb-48ee-893b-e8d7819fb0cd.png)

**Comment by sisoe24** [comment]
Is the command installed on your system? The command `hs.ipc.cliStatus()` should return `true` when executing inside hammerspoon console. Also the `require('hs.ipc')` must be the first statement of your `init.lua`

From the docs

>  The command line tool will not work unless the hs.ipc module is loaded first, so it is recommended that you add require("hs.ipc") to your Hammerspoon init.lua file (usually located at ~/.hammerspoon/init.lua) so that it is always available when Hammerspoon is running.

**Comment by apotenza92** [comment]
Issue was with Apple Silicone and the Homebrew install of Hammerspoon. Resolved by using advice [here](https://github.com/Hammerspoon/hammerspoon/issues/2930#issuecomment-899092002) and running `hs.ipc.cliInstall("/opt/homebrew")`
