### ISSUE TITLE
hs completion not working

### ISSUE THREAD

**Issue by 343max** [sisoe24/hammerspoon-vscode#2]
Hey!

I can't get the extension to work. What might I do to debug this issue?

<img width="426" alt="image" src="https://user-images.githubusercontent.com/33906/214886164-7eb43f97-0000-4e43-9bd6-7306662a7934.png">

**Comment by sisoe24** [comment]
Hey, thanks for reaching out!

I believe the error comes from the Lua language server (which shouldn't bother the hammerspoon extension as it does not rely on it). If you keep typing by adding a `.`, you should receive the suggestions. They might be buried down based on what your text editor prioritizes first, such as a list of text words.

But I now notice that I receive duplicate suggestions, which shouldn't happen.

Let me know after you try if it works for you.

![hs](https://user-images.githubusercontent.com/28490646/214909180-e317bb54-e198-46a7-81d2-b2e60b4cdce2.gif)

**Comment by sisoe24** [comment]
I will close this issue for now. If the problem continues, feel free to open it again.

**Comment by 343max** [comment]
Sorry, thank you so much for your extensive reply! Sorry I missed the github notification, otherwise I would have responded right away.

Thank you!
